function ::= 'fn' identifier '('  ')' '{' statement* '}'
;

statement ::= print_statement
	| definition
	| declaration
	| assign
;

expression ::= indentifier
	| indentifier '+' expression
	| indentifier '-' expression
	| indentifier '*' expression
	| indentifier '/' expression
	| indentifier '==' expression
	| '-' expression
;

print_statement ::= 'print' '(' expression ')' ';'
;

definition ::= type identifier
;

declaration ::= type identifier ':' literal ';'
;

assign ::= identifier ':' literal
;

type ::= 'int' | 'str' | 'float'
;

literal ::= number | decimal | string
;

identifier ::= [a-z] ([a-z] | [0-9] | '_')*
;